throw new Error("Error occurs.")